<a href="https://colab.research.google.com/github/suhys18/AI/blob/main/ann_for_COVID_19_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [ ]:
dataset = pd.read_csv("covid-19 symptoms dataset.csv")
x = dataset.iloc[: , :-1].values
y = dataset.iloc[: , -1].values

In [ ]:
print(x)

[[102   0   9   0  -1]
 [102   0  10   0   0]
 [104   0  33   1  -1]
 ...
 [101   0  44   1   0]
 [102   0  97   0  -1]
 [104   1  62   1  -1]]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size = 0.2,random_state = 42)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
ann = tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))


In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))


In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [ ]:
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

In [ ]:
ann.fit(x_train,y_train, batch_size = 18,epochs = 180)